version: '3.8'
services:
  # MySQL Database
  mysql:
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: passwd
    ports:
      - "3306:3306"

  # Apache Kafka
  kafka:
    image: confluentinc/cp-kafka:6.2.0
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  # Zookeeper (Required by Kafka)
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
